version: '2'
services:
  mariadb:
    build:
          context: .
          dockerfile: Dockerfile.mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
    volumes:
      - dbdata:/var/lib/mysql
    ports:
     - "127.0.0.1:3306:3306"
    expose:
     - "3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8001:80"
    depends_on:
      - mariadb
    links:
      - mariadb:db

volumes:
  dbdata:
